# Generated by Django 5.1 on 2024-09-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_register_address_register_eduction_register_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='eduction',
            new_name='education',
        ),
    ]
