# Generated by Django 5.1 on 2024-10-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contect_message',
        ),
    ]
