# Generated by Django 5.1 on 2024-10-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_contect_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
    ]
