# Generated by Django 5.1 on 2024-10-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlist_add',
        ),
    ]
