# Generated by Django 5.1 on 2024-10-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_rename_wishlist_wishlist_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist_add',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.product'),
        ),
    ]
