# Generated by Django 5.1 on 2024-10-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_wishlist_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist_add',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.register'),
        ),
    ]
