# Generated by Django 5.1 on 2024-10-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_cart1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart1',
            new_name='add_to_cart',
        ),
    ]
