# Generated by Django 5.1 on 2024-10-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checkout',
            new_name='checkout_page',
        ),
    ]
