# Generated by Django 5.1 on 2024-11-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0021_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_review',
            name='name',
        ),
    ]
