# Generated by Django 5.1 on 2024-11-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0022_remove_user_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_review',
            old_name='rating',
            new_name='rate',
        ),
    ]
