# Generated by Django 5.1 on 2024-11-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0023_rename_rating_user_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_review',
            old_name='rate',
            new_name='rating',
        ),
    ]
