# Generated by Django 5.1 on 2024-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0025_alter_user_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
