# Generated by Django 5.1 on 2024-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0029_user_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coupon',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
