# Generated by Django 5.1 on 2025-01-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0030_user_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_page',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout_page',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='checkout_page',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='checkout_page',
            name='state',
        ),
        migrations.RemoveField(
            model_name='checkout_page',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='checkout_page',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkout_page',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
