# Generated by Django 5.1 on 2025-01-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0031_remove_checkout_page_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_page',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.register'),
        ),
    ]
