# Generated by Django 5.1 on 2025-01-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0035_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
