# Generated by Django 5.1 on 2025-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0037_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
